comment "Exported from Arsenal by LIM";
private ["_unit"];
_unit = _this select 0;
comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
_unit forceAddUniform "rhs_uniform_gorka_r_g";
for "_i" from 1 to 10 do {this addItemToUniform "ACE_elasticBandage";};
_unit addItemToUniform "ACE_plasmaIV_500";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 3 do {this addItemToUniform "ACE_epinephrine";};
for "_i" from 1 to 4 do {this addItemToUniform "ACE_tourniquet";};
_unit addVest "LOP_V_6Sh92_Vog_OLV";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_white";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_plamyam";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgd5";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_GDM40";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_VOG25";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_545x39_S_AK";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_VG40TB";};
_unit addBackpack "CUP_B_RUS_Backpack";
_unit addItemToBackpack "rhs_1PN138";
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_plasmaIV";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_plasmaIV_250";};
_unit addItemToBackpack "ACE_EarPlugs";
_unit addItemToBackpack "ACE_DAGR";
_unit addItemToBackpack "ACE_Flashlight_XL50";
_unit addItemToBackpack "ACE_DefusalKit";
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_IR_Strobe_Item";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_30Rnd_545x39_EP_ak";};
for "_i" from 1 to 3 do {this addItemToBackpack "APERSTripMine_Wire_Mag";};
_unit addHeadgear "rhs_zsh12";
_unit addGoggles "G_Balaclava_oli";

comment "Add weapons";
_unit addWeapon "hlc_rifle_ak12GL";
_unit addPrimaryWeaponItem "rhs_acc_dtk4short";
_unit addPrimaryWeaponItem "rhsusf_acc_anpeq15A";
_unit addPrimaryWeaponItem "rhsusf_acc_compm4";
_unit addWeapon "CUP_hgun_PB6P9";
_unit addHandgunItem "CUP_muzzle_PB6P9";
_unit addWeapon "ACE_VectorDay";

comment "Set Medical Class";
_unit setVariable ["ace_medical_medicClass",2];